# Generated by Django 4.1.2 on 2022-10-20 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loginAndRegister', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_order_number', models.CharField(max_length=100)),
                ('purchase_order_date', models.CharField(max_length=100)),
                ('delivery_date', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=0)),
                ('total_amount', models.CharField(blank=True, max_length=100)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='loginAndRegister.company')),
            ],
        ),
        migrations.CreateModel(
            name='OderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('quantity', models.CharField(blank=True, max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='loginAndRegister.product')),
                ('purchase_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='loginAndRegister.purchaseorder')),
            ],
        ),
    ]
