# Generated by Django 4.1.2 on 2022-11-02 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginAndRegister', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='delivery_date',
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='delivery_date',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
