# Generated by Django 4.1.2 on 2022-11-02 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginAndRegister', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challan',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
