# Generated by Django 4.1.2 on 2022-11-02 12:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('loginAndRegister', '0002_remove_purchaseorder_delivery_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_price',
            field=models.FloatField(blank=True),
        ),
    ]
