# Generated by Django 4.1.2 on 2022-11-28 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginAndRegister', '0004_rename_date_orderdetail_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_id',
            new_name='product_code',
        ),
    ]
