# Generated by Django 4.1.2 on 2022-11-28 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginAndRegister', '0005_rename_product_id_product_product_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='product',
        ),
        migrations.RemoveField(
            model_name='challan',
            name='product',
        ),
    ]
