# Generated by Django 4.1.2 on 2022-12-01 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loginAndRegister', '0006_remove_bill_product_remove_challan_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='order_detail',
        ),
        migrations.AddField(
            model_name='challan',
            name='bill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='loginAndRegister.bill'),
        ),
    ]
