# Generated by Django 4.1.2 on 2022-12-01 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginAndRegister', '0007_remove_bill_order_detail_challan_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='payment_terms',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='quantity',
            field=models.IntegerField(blank=True, max_length=100),
        ),
    ]
