# Generated by Django 3.0.5 on 2022-12-02 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginAndRegister', '0008_company_payment_terms_alter_orderdetail_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='price',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='total_amount',
        ),
    ]
