# Generated by Django 4.1.2 on 2022-12-05 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loginAndRegister', '0009_auto_20221202_0719'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='loginAndRegister.company'),
        ),
        migrations.AlterField(
            model_name='challan',
            name='bill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='challan', to='loginAndRegister.bill'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='quantity',
            field=models.IntegerField(blank=True),
        ),
    ]
